name: MultiBans
version: 0.1.1
main: me.kvalbrus.multibans.bukkit.BukkitPlugin
api-version: 1.19
authors: [ kvalbrus ]
description: Plugin for minecraft

commands:
  ban:
    permission: multibans.punishment.ban.execute;multibans.punishment.tempban.execute
  banip:
    permission: multibans.punishment.banip.execute;multibans.punishment.tempbanip.execute
  mute:
    permission: multibans.punishment.mutechat.execute;multibans.punishment.tempmutechat.execute
  kick:
    permission: multibans.punishment.kick.execute
  unban:
    permission: multibans.punishment.unban.execute
  unmute:
    permission: multibans.punishment.unmutechat.execute
  punish:
    permission: multibans.command.reason;multibans.command.comment
  multibans:
    permission: multibans.command.reload
    aliases: [ mb ]
  history:
    permission: multibans.command.history
  iphistory:
    permission: multibans.command.iphistory
  ipcheck:
    permission: multibans.command.ipcheck
permissions:
  multibans.punishment.ban.*:
    children:
      multibans.punishment.ban.execute: true
      multibans.punishment.ban.listen: true

  multibans.punishment.tempban.*:
    children:
      multibans.punishment.tempban.execute: true
      multibans.punishment.tempban.listen: true

  multibans.punishment.banip.*:
    children:
      multibans.punishment.banip.execute: true
      multibans.punishment.banip.listen: true

  multibans.punishment.tempbanip.*:
    children:
      multibans.punishment.tempbanip.execute: true
      multibans.punishment.tempbanip.listen: true

  multibans.punishment.mutechat.*:
    children:
      multibans.punishment.mutechat.execute: true
      multibans.punishment.mutechat.listen: true

  multibans.punishment.tempmutechat.*:
    children:
      multibans.punishment.tempmutechat.execute: true
      multibans.punishment.tempmutechat.listen: true

  multibans.punishment.kick.*:
    children:
      multibans.punishment.kick.execute: true
      multibans.punishment.kick.listen: true

  multibans.punishment.command.reload:
    default: op
  multibans.punishment.unban.*:
    children:
      multibans.punishment.unban.execute: true
      multibans.punishment.unban.listen: true

  multibans.punishment.unmutechat.*:
    children:
      multibans.punishment.unmutechat.execute: true
      multibans.punishment.unmutechat.listen: true

  multibans.command.comment:
    default: op
  multibans.command.reason:
    default: op

  multibans.command.history:
    default: op
  multibans.command.iphistory:
    default: op
  multibans.command.ipcheck:
    default: op