name: build

on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

  tests:
#    needs: [ build ]
    name: tests
    runs-on: ubuntu-latest

    services:
      server:
        image: itzg/minecraft-server
        ports:
          - 25565:25565
    steps:
      - name: "> Checkout repository <"
        uses: actions/checkout@v3
      - name: "> Run server <"
        run: /usr/bin/docker run -d -it -p 25565:25565 -e EULA=TRUE itzg/minecraft-server